### ISSUE TITLE
For 2nd exercise, the string that prints the help statement is too long

### ISSUE THREAD

**Issue by billhathaway** [gophergala/learn-Go-the-hard-way#1]
the help statement 
println("Please edit main.go,and complete the 'Sum' function for the parallel sum to pass the test.\nConcurrency is the most important feature of Go,and the principle is\n'Do not communicate by sharing memory; instead, share memory by communicating.'\nIn this exercise you need to catch many features of channels.This is a tour for you to figure out!")

just prints [string too long]

If you want to use the builtin println you need to split it up the long string, or you can switch to fmt.Println which can print the whole string

**Comment by ggaaooppeenngg** [comment]
@billhathaway  What's your Go version?

**Comment by billhathaway** [comment]
go version
go version go1.4 darwin/amd64

**Comment by ggaaooppeenngg** [comment]
@billhathaway  it works on  go1.4 linux/amd64,so I didn't catch the error.
I use single quote '' to unescape the string in the later exercises.
Thx,I will fix it in the [fork repository](https://github.com/ggaaooppeenngg/learn-Go-the-hard-way).

**Comment by ggaaooppeenngg** [comment]
fix
