### ISSUE TITLE
l4 question

### ISSUE THREAD

**Issue by WIZARD-CXY** [gophergala/learn-Go-the-hard-way#10]
@ggaaooppeenngg  I have a question on l4, Below is my temp solution.
https://github.com/WIZARD-CXY/learn-Go-the-hard-way/blob/l4r/main.go

If the test is original `var f func(func(e int) int, []int) []int.`
I cant't make it work. It always panic reflect: wrong return count from function created by MakeFunc
But if I change to `var f func(func(e int) int, []int) (int, int ,int)` it is ok.
Do you know why??

**Comment by WIZARD-CXY** [comment]
Thanks in advance

**Comment by ggaaooppeenngg** [comment]
For reflect,[]int is just one element. How do you differentiate from ([]int) and ([][]int) and ([]int,[]int,[]int)?
The first two are "one element" while the last is "tree element".
Please reference [here](https://golang.org/pkg/reflect/#MakeSlice) for details about how to make a slice as one element.

**Comment by WIZARD-CXY** [comment]
I got it, although I don't use MakeSlice
