### ISSUE TITLE
Solution to the Problems

### ISSUE THREAD

**Issue by shubhamagarwal003** [gophergala/learn-Go-the-hard-way#13]
Any plans to publish solutions to these problems?

**Comment by ggaaooppeenngg** [comment]
You can find solutions in git log, I removed answer before I made a tag.

**Comment by jianhaiqing** [comment]
I can't find l1's solution. I really work hard to figure it out , but failed at last. 
Can you publish the l1's solution ? Many thanks for your fancy work.

**Comment by jianhaiqing** [comment]
I only figure out how to reverse the slice and don't know how to deal with PTR.
https://play.golang.org/p/JLR1DLEHa4A
I don't fine solution from git log. Hope to get your answer. 
I really appreciate what you have done, it's awesome, dry me to dig the answer.

**Comment by ggaaooppeenngg** [comment]
@jianhaiqing https://github.com/gophergala/learn-Go-the-hard-way/commit/73051ce44f76b113aca3fd468de8a62d5d543f4f this is l2 answer for example, which answer are you looking for?

**Comment by jianhaiqing** [comment]
l1 for Reverse 
func Reverse(slice interface{}) {
// do something
}
func TestReverse(t *testing.T) {
	var slice = []myType{0, 1, 2}
	Reverse(&slice)
	if slice[0] != myType(2) || slice[1] != myType(1) || slice[2] != myType(0) || len(slice) != 3 {
		t.Fail()
	}
}

**Comment by ggaaooppeenngg** [comment]
@jianhaiqing  Manual method https://github.com/golang/go/wiki/SliceTricks#reversing and for library solution 
```
package main

import (
	"fmt"
	"sort"
)

func main() {
	s := []int{5, 2, 6, 3, 1, 4} // unsorted
	sort.Sort(sort.Reverse(sort.IntSlice(s)))
	fmt.Println(s)
}
```

**Comment by jianhaiqing** [comment]
according to the tips from the main method ;
```
func main() {
println("Please edit main.go,and complete the 'Reverse' function to pass the test.\n   /
You should use reflect package to reflect the slice type and make it applly to any type.\n  /
To run test,please run 'go test'\nIf you pass the test,please run 'git checkout l2' ")
}
```
For the moment, i can't figure out how to deal with the PTR type(&slice), look at  the snippets  as follow:

```
package main

import (
	"fmt"
	"reflect"
)

func ReverseSlice(s interface{}) {
	size := reflect.ValueOf(s).Len()
	swap := reflect.Swapper(s)
	for i, j := 0, size-1; i < j; i, j = i+1, j-1 {
		swap(i, j)
	}
}
func main() {
	a := []int{48, 44, 37, 40, 14, 45, 8, 38, 12, 3}
	ReverseSlice(a)
	fmt.Println(a)
}
```
It can deal all kinds of type, include []string, but failed to deal the PTR type. That's my issue.
Thanks for your answer.

**Comment by ggaaooppeenngg** [comment]
https://golang.org/pkg/reflect/#Value.Elem you can use this function.

**Comment by jianhaiqing** [comment]
i tried, but failed. I don't how to iterate the Elem. 
```
//Reverse reverses a slice.
func Reverse(slice interface{}) {
	arrays := reflect.ValueOf(slice)
	if arrays.Kind() == reflect.Ptr {
		arrays = arrays.Elem()
	}
	swap := reflect.Swapper(arrays.Interface)
	for i, j := 0, arrays.Len()-1; i < arrays.Len()/2+1; i, j = i+1, j-1 {
		swap(i, j)
	}
}
```
The snippets above fail to pass the test. Can you give me the exact solution directly ?

**Comment by jianhaiqing** [comment]
looking forward to your reply.

**Comment by rohmanhm** [comment]
I also had a problem with the reference pointer.

**Comment by Lunaticf** [comment]
> i tried, but failed. I don't how to iterate the Elem.
> 
> ```
> //Reverse reverses a slice.
> func Reverse(slice interface{}) {
> 	arrays := reflect.ValueOf(slice)
> 	if arrays.Kind() == reflect.Ptr {
> 		arrays = arrays.Elem()
> 	}
> 	swap := reflect.Swapper(arrays.Interface)
> 	for i, j := 0, arrays.Len()-1; i < arrays.Len()/2+1; i, j = i+1, j-1 {
> 		swap(i, j)
> 	}
> }
> ```
> The snippets above fail to pass the test. Can you give me the exact solution directly ?

//Reverse reverses a slice.
var Reverse = func(slice interface{}) {
	s := reflect.ValueOf(slice)
	if s.Kind() == reflect.Ptr {
		s = s.Elem()
	}
	i := 0
	j := s.Len() - 1
	for i < j {
		x, y := s.Index(i).Interface(), s.Index(j).Interface()
		s.Index(i).Set(reflect.ValueOf(y))
		s.Index(j).Set(reflect.ValueOf(x))
		i++
		j--
	}
}

This way works.But it is not elegant. Look forward to better solution....

**Comment by Lunaticf** [comment]
> i tried, but failed. I don't how to iterate the Elem.
> 
> ```
> //Reverse reverses a slice.
> func Reverse(slice interface{}) {
> 	arrays := reflect.ValueOf(slice)
> 	if arrays.Kind() == reflect.Ptr {
> 		arrays = arrays.Elem()
> 	}
> 	swap := reflect.Swapper(arrays.Interface)
> 	for i, j := 0, arrays.Len()-1; i < arrays.Len()/2+1; i, j = i+1, j-1 {
> 		swap(i, j)
> 	}
> }
> ```
> The snippets above fail to pass the test. Can you give me the exact solution directly ?

```
//Reverse reverses a slice.
var Reverse = func(slice interface{}) {
	s := reflect.ValueOf(slice)
	if s.Kind() == reflect.Ptr {
		s = s.Elem()
	}
	i := 0
	j := s.Len() - 1
	for i < j {
		x, y := s.Index(i).Interface(), s.Index(j).Interface()
		s.Index(i).Set(reflect.ValueOf(y))
		s.Index(j).Set(reflect.ValueOf(x))
		i++
		j--
	}
}
```
This way works.But it is not elegant.Look forward to a better solution....Thanks

**Comment by yabay2009** [comment]
> @jianhaiqing [73051ce](https://github.com/gophergala/learn-Go-the-hard-way/commit/73051ce44f76b113aca3fd468de8a62d5d543f4f) this is l2 answer for example, which answer are you looking for?

很感谢这个教程....
想问一下这个题解，顺着链接过去的commit history并没有答案啊...

万分感谢..
