### ISSUE TITLE
found some l1 test bug 

### ISSUE THREAD

**Issue by WIZARD-CXY** [gophergala/learn-Go-the-hard-way#4]
Just finish the l1 test. I think the reverse test code should be 

```
if slice[0] != myType(2) || slice[1] != myType(1) || slice[2] != myType(0) || len(slice) != 3 {
        t.Fail()
}

```

otherwise if we don't reverse the slice and just use the old slice which is [0,1,2], it passes the test

**Comment by WIZARD-CXY** [comment]
maybe just a subtle bug,never mind

**Comment by ggaaooppeenngg** [comment]
fixed [commit fbe9ac](https://github.com/gophergala/learn-Go-the-hard-way/commit/fbe9ac513a3929d08e827ec2bebb21fec8f398d3)
